// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiIRdm29Ipeh-7epH6Tj_AZl8QMrtg2nI',
    appId: '1:1027063545082:web:44bf019e823d29cd781d43',
    messagingSenderId: '1027063545082',
    projectId: 'qrcode-verification',
    authDomain: 'qrcode-verification.firebaseapp.com',
    storageBucket: 'qrcode-verification.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgCkdtKQTU84wXkj6R9oEskAjqVMjWqPI',
    appId: '1:1027063545082:android:df15e78933a5d5af781d43',
    messagingSenderId: '1027063545082',
    projectId: 'qrcode-verification',
    storageBucket: 'qrcode-verification.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEJ1yYalnk642z2aRoSgZN6qmUAaq_6DM',
    appId: '1:1027063545082:ios:105331459333abd0781d43',
    messagingSenderId: '1027063545082',
    projectId: 'qrcode-verification',
    storageBucket: 'qrcode-verification.appspot.com',
    iosBundleId: 'com.example.qrcodeVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEJ1yYalnk642z2aRoSgZN6qmUAaq_6DM',
    appId: '1:1027063545082:ios:34fb391dfa4a313a781d43',
    messagingSenderId: '1027063545082',
    projectId: 'qrcode-verification',
    storageBucket: 'qrcode-verification.appspot.com',
    iosBundleId: 'com.example.qrcodeVerification.RunnerTests',
  );
}
